changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feat
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bug
    - title: 📝 Documentation
      labels:
        - docs
    - title: ⚙️ Maintenance
      labels:
        - chore
        - ci
        - refactor
        - style
        - test
  exclude:
    labels:
      - skip-changelog
    authors:
      - octocat
