#!/usr/bin/env python3
import sys, os

sys.path.append("/usr/lib/wrtgram")
sys.path.append("/usr/lib/wrtgram/plugins/ctx")

import wrtapi
import helper

if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit(0)
        
    command = sys.argv[1]
    prompt = sys.argv[2]
    
    helper.send_ctx_list(wrtapi.CHAT_ID, "interface", command, prompt)
