#!/bin/sh

. /usr/lib/wrtgram/common

command="$1"
text="$2"

INTERFACES=$(ubus list network.interface.* | awk -F"." '{printf " [ {\"callback_data\": \"##CMD##|"$3"\^\" ,\"text\" : \""$3"\"} ],"}')

# POSIX-compatible string manipulation
rules=$(echo "$INTERFACES" | sed 's/,$//')
rls=$(echo "$rules" | sed "s/##CMD##/$command/g")
keyboard="{\"inline_keyboard\": [$rls] }"

tg_api_call "sendMessage" \
    -d "chat_id=${WRTGRAM_CHAT_ID}" \
    -d "parse_mode=Markdown" \
    -d "reply_markup=${keyboard}" \
    --data-urlencode "text=${text}"
