#!/bin/sh

. /usr/lib/wrtgram/common

command="$1"
text="$2"

# List init scripts and format for inline keyboard
SERVICES=$(ls -1 /etc/init.d/ | awk '{printf " [ {\"callback_data\": \"##CMD##|"$0"\^\" ,\"text\" : \""$0"\"} ],"}')

# POSIX-compatible string manipulation
rules=$(echo "$SERVICES" | sed 's/,$//')
rls=$(echo "$rules" | sed "s/##CMD##/$command/g")
keyboard="{\"inline_keyboard\": [$rls] }"

tg_api_call "sendMessage" \
    -d "chat_id=${WRTGRAM_CHAT_ID}" \
    -d "parse_mode=Markdown" \
    -d "reply_markup=${keyboard}" \
    --data-urlencode "text=${text}"
