#!/bin/sh

. /usr/lib/wrtgram/common

command="$1"
text="$2"

# Extract wireless radios and format for inline keyboard
wireless=$(uci -q show wireless | grep "default_radio" | grep ssid | grep -oE "[[:digit:]]+.ssid='([[:graph:]]|[[:blank:]])+'" | awk -F ".ssid=" '{
    gsub(/[\047]|\[|\]/,"",$1);
    gsub(/[\047]/,"",$2);
    printf "[ {\"callback_data\": \"##CMD##|" $1 "\^" $2 "\" ,\"text\" : \"" $2;
    cmd = "[ \"$(uci -q get wireless.radio" $1 ".__toggle)\" = \"Disable\" ] && echo -en \" (Disabled)\" || echo -en \" (Enabled)\"";
    system(cmd);
    print "\"} ],";
}')

# POSIX-compatible string manipulation
rules=$(echo "$wireless" | sed 's/,$//')
rls=$(echo "$rules" | sed "s/##CMD##/$command/g")
keyboard="{\"inline_keyboard\": [$rls] }"

tg_api_call "sendMessage" \
    -d "chat_id=${WRTGRAM_CHAT_ID}" \
    -d "reply_markup=${keyboard}" \
    -d "text=${text}"
