#!/usr/bin/env python3
"""
fw_list.py – Firewall rules plugin (replaces shell plugins/fw_list)

Parses `uci show firewall`, prints a formatted rule list.
The inline keyboard is generated by bot.py using ctx data.
"""

import re
import subprocess
import sys


def _uci_show_firewall() -> str:
    result = subprocess.run(
        ["uci", "-q", "show", "firewall"],
        capture_output=True, text=True,
    )
    return result.stdout


def _uci_get(key: str) -> str:
    result = subprocess.run(
        ["uci", "-q", "get", key],
        capture_output=True, text=True,
    )
    return result.stdout.strip()


def main() -> None:
    raw  = _uci_show_firewall()
    # Collect rule indices that have a name
    indices = {}
    for line in raw.splitlines():
        m = re.search(r"firewall\.@rule\[(\d+)\]\.name='([^']+)'", line)
        if m:
            indices[m.group(1)] = m.group(2)

    if not indices:
        print("*Firewall Rules*\n\n_(No rules found.)_")
        return

    print("🔥 *Firewall Rules*\n")
    for idx in sorted(indices, key=int):
        name    = indices[idx]
        enabled = _uci_get(f"firewall.@rule[{idx}].enabled")
        src     = _uci_get(f"firewall.@rule[{idx}].src")
        dest    = _uci_get(f"firewall.@rule[{idx}].dest")
        target  = _uci_get(f"firewall.@rule[{idx}].target")
        proto   = _uci_get(f"firewall.@rule[{idx}].proto") or "all"
        dest_ip = _uci_get(f"firewall.@rule[{idx}].dest_ip")

        state_icon = "🔴 Disabled" if enabled == "0" else "🟢 Enabled"

        print(f"*[{idx}] {name}*  —  {state_icon}")
        if src:
            print(f"  Src zone: `{src}`")
        if dest:
            print(f"  Dst zone: `{dest}`")
        if dest_ip:
            print(f"  Dst IP: `{dest_ip}`")
        print(f"  Proto: `{proto}`  |  Target: `{target}`")
        print()


if __name__ == "__main__":
    main()
