#!/bin/sh
# HELP: Remove a hostname from a deny firewall rule, if hostname is empty, will remove all rules created by this bot.

NAME="$1" 

TOTAL=0
for rule in $(uci -q show firewall | grep "Telegram ${NAME}" | grep -oE "\[([[:digit:]])\]")
do
	uci -q delete firewall.@rule${rule}
	TOTAL=$(($TOTAL+1))
done

if [ $TOTAL > 0 ]; then
	uci -q commit firewall &> /dev/null
	/etc/init.d/firewall restart &> /dev/null
	echo "Deleted $TOTAL rules !"
	return 0
fi
return 1
