#!/bin/sh
# HELP: Ping a address or host, return Up or Down.

DEVICE="$1"

# POSIX-compatible check and redirection
ping "${DEVICE}" -w 1 -c 1 -q >/dev/null 2>&1
if [ $? = 0 ]; then
    printf "Up"
else
    printf "Down"
fi
printf "\n"
