#!/bin/sh
# HELP: Get the Organization that onwer the MacAddr.

. /usr/lib/wrtgram/common

# POSIX-compatible string slicing and substitution
PUREMAC=$(echo "$1" | cut -c 1-8)
LMAC=$(echo "$PUREMAC" | awk '{ print toupper($0) }')
MAC=$(echo "$LMAC" | sed 's/://g')

# Use common TLS helper for the API call
maclist=$(curl -s ${CURL_TLS} -L -X GET -H "Content-Type: application/json; charset=utf-8" \
	-H "Origin: https://regauth.standards.ieee.org" \
	-H "Referer: https://regauth.standards.ieee.org/standards-ra-web/pub/view.html" \
	"https://services13.ieee.org/RST/standards-ra-web/rest/assignments/?registry=MA-L&sortby=organization&sortorder=asc&text=${MAC}")

IDS=$(echo "$MAC" | sed 's/-//g')
HEX=$(jsonfilter -s "$maclist" -e $.data.hits[*].assignmentNumberHex)

i=0
for hexs in $HEX; do
	if [ "$hexs" = "$IDS" ]; then
		name=$(jsonfilter -s "$maclist" -e "$.data.hits[$i].organizationName")
		echo "Organization: $name"
		exit 0
	fi
	i=$((i + 1))
done

echo "Organization: Not Found!"
