#!/bin/ash
# HELP: Shows the list of ignored mac addresses that will not be notified by the bot.
ignored_macaddrs_file=$(uci -q get wrtgram.global.ignored_macaddrs_file)

echo "*Ignored MAC Addresses*"
cat "$ignored_macaddrs_file"
