#!/bin/sh

# POSIX-compatible way to set IFS to newline
IFS='
'
PORTS=$(swconfig dev switch0 show 2>/dev/null | grep link | grep -oE "port:[[:digit:]][[:space:]]link:(up|down)([[:space:]]speed:[[:digit:]]+|$)")

for port in $PORTS; do
    id=$(echo "$port" | grep -oE "port:[[:digit:]]" | cut -d ':' -f 2)
    case "$id" in
        0) echo "CPU-0" ;;
        1) echo "LAN 1" ;;
        2) echo "LAN 2" ;;
        3) echo "LAN 3" ;;
        4) echo "LAN 4" ;;
        5) echo "WAN"   ;;
        6) echo "CPU-1" ;;
    esac
    # POSIX-compatible way to replace space with newline
    echo "$port" | tr ' ' '\n'
    echo ""
done
