#!/usr/bin/env python3
"""
wifi_list.py – WiFi network plugin (replaces shell plugins/wifi_list)

Parses `uci show wireless`, calls iwinfo for live signal data,
prints a formatted SSID list.
The inline keyboard (enable/disable buttons) is generated by bot.py.
"""

import re
import subprocess
import sys


def _uci_get(key: str) -> str:
    r = subprocess.run(["uci", "-q", "get", key], capture_output=True, text=True)
    return r.stdout.strip()


def _uci_show_wireless() -> str:
    r = subprocess.run(["uci", "-q", "show", "wireless"], capture_output=True, text=True)
    return r.stdout


def _iwinfo(iface: str, field: str) -> str:
    """Run iwinfo <iface> info and extract a named field (best-effort)."""
    try:
        r = subprocess.run(
            ["iwinfo", iface, "info"],
            capture_output=True, text=True, timeout=3,
        )
        for line in r.stdout.splitlines():
            if field.lower() in line.lower():
                return line.strip()
    except Exception:
        pass
    return ""


def main() -> None:
    raw = _uci_show_wireless()

    # Gather SSIDs by index
    ssids: dict[str, str] = {}
    for line in raw.splitlines():
        m = re.search(r"default_radio(\d+)\.ssid='([^']+)'", line)
        if m:
            ssids[m.group(1)] = m.group(2)

    if not ssids:
        print("*Wireless*\n\n_(No SSIDs found.)_")
        return

    print("📡 *WiFi Networks*\n")

    for idx in sorted(ssids, key=int):
        ssid  = ssids[idx]
        radio = _uci_get(f"wireless.radio{idx}.type") or "radio"
        band  = _uci_get(f"wireless.radio{idx}.band") or ""
        chan  = _uci_get(f"wireless.radio{idx}.channel") or "auto"
        toggle = _uci_get(f"wireless.radio{idx}.__toggle")
        disabled = _uci_get(f"wireless.default_radio{idx}.disabled")

        if toggle == "Disable" or disabled == "1":
            state_icon = "🔴 Disabled"
        else:
            state_icon = "🟢 Enabled"

        iface = f"wlan{idx}"
        rate_line = _iwinfo(iface, "Bit Rate")
        qual_line = _iwinfo(iface, "Link Quality")

        # Extract numeric rate e.g. "144.4 MBit/s"
        rate_m = re.search(r"[\d.]+\s*MBit/s", rate_line)
        rate   = rate_m.group(0) if rate_m else "N/A"

        # Extract quality e.g. "65/70"
        qual_m = re.search(r"(\d+)/(\d+)", qual_line)
        if qual_m:
            numerator   = int(qual_m.group(1))
            denominator = int(qual_m.group(2))
            pct  = int(numerator * 100 / denominator)
            qual = f"{pct}%"
        else:
            qual = "N/A"

        print(f"*[{idx}] {ssid}*  —  {state_icon}")
        print(f"  Radio: `{radio}`  Band: `{band}`  Channel: `{chan}`")
        print(f"  Rate: `{rate}`  |  Quality: `{qual}`")
        print()


if __name__ == "__main__":
    main()
