#!/bin/ash

export PATH='/usr/bin:/usr/sbin:/bin:/sbin'

has_offer=0
count=0
switch=$(swconfig list | awk '{printf $4}')

(logread -f |while read line; do
	echo "${line}" | grep -q "$switch: Port"
	if [ $? == 0 ]; then
		ports=$(echo "${line}" | grep -oE "Port ([0-9]+) is (up|down)")
		time=$(date +"%I:%M:%S %p")
		pnum=$(echo "${ports}" | cut -d ' ' -f 2)	
		state=$(echo "${ports}" | cut -d ' ' -f 4)	
		if [ "$state" == "up" ]; then
			icon="🟢"
		else
			icon="🔴"
		fi
		telegram=$(echo "${icon} *LAN Port Alert* ${icon}"$'

'"*Port:* ${pnum}"$'
'"*Time:* ${time}"$'
'"*State:* ${state}")
		/sbin/telebot "$telegram"
	fi
	echo "${line}" | grep -q "DHCPOFFER" 
	if [ $? == 0 ]; then
		has_offer=1
		count=4
	fi

	echo "${line}" | grep -q "DHCPACK" 
	if [ $? == 0 ] && [ $has_offer == 1 ]; then 
		dados=$(echo "${line}" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} \w{2}:\w{2}:\w{2}:\w{2}:\w{2}:\w{2} .*")
		if [ "${dados}" == "" ];then
			dados=$(echo "${line}" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} \w{2}:\w{2}:\w{2}:\w{2}:\w{2}:\w{2}")
		fi
		time=$(date +"%I:%M:%S %p")
		ip=$(echo "${dados}" | cut -d ' ' -f 1)
		macaddr=$(echo "${dados}" | cut -d ' ' -f 2)
		name=$(echo "${dados}" | cut -d ' ' -f 3 | awk '{gsub("*","\*",$0); gsub( "_","\\_", $0 );  printf $0 }')
		if [ "${name}" == "" ];then
			name="N/A"
		fi
		ignored_macaddrs_file=$(uci -q get wrtgram.global.ignored_macaddrs_file)
		if ! grep -q "$macaddr" $ignored_macaddrs_file; then
			telegram=$(echo "🆕 *New Device Connected* 🆕"$'

'"*Hostname:* ${name}"$'
'"*Time:* ${time}"$'
'"*IP Address:* ${ip}"$'
'"*MAC Address:* ${macaddr}")
			/sbin/telebot "$telegram"
			has_offer=0
		else
			echo "Ignored macaddr found in ignore list"
		fi
	fi
	if [ $count == 0 ]; then
		has_offer=0
	else
		count=$((count-1))
	fi
done)&