#!/bin/sh

. /usr/lib/wrtgram/common

command="$1"

# Escape underscores for Markdown (POSIX-compatible via sed)
command_new=$(echo "$command" | sed 's/_/\\_/g')

tg_api_call "sendMessage" \
    -d "chat_id=${WRTGRAM_CHAT_ID}" \
    -d "parse_mode=Markdown" \
    --data-urlencode "text=${command_new}" \
    | logger -t "telegram_bot[$$]" -p daemon.info
