#!/usr/bin/env python3

import sys, os, json

sys.path.append("/usr/lib/wrtgram")
try:
    import wrtapi
except ImportError:
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../usr/lib/wrtgram')))
    import wrtapi

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(0)
        
    items = sys.argv[1].split('\n')
    full = ""
    for item in items:
        if not item and item is items[-1]: continue
        
        item_len = len(item.encode('utf-8'))
        
        if len(full.encode('utf-8')) + item_len + 1 > 4096:
            resp = wrtapi.tg_api_call("sendMessage", form_data={"chat_id": wrtapi.CHAT_ID, "parse_mode": "Markdown"}, data_urlencode={"text": full})
            if not resp or str(resp.get('ok')).lower() != "true":
                wrtapi.log_msg("telegram_sender", f"API Error: {json.dumps(resp) if resp else 'Connection failed'}")
            full = item
        else:
            if not full:
                full = item
            else:
                full = full + "\n" + item

    if full:
        resp = wrtapi.tg_api_call("sendMessage", form_data={"chat_id": wrtapi.CHAT_ID, "parse_mode": "Markdown"}, data_urlencode={"text": full})
        if not resp or str(resp.get('ok')).lower() != "true":
            wrtapi.log_msg("telegram_sender", f"API Error: {json.dumps(resp) if resp else 'Connection failed'}")

