#!/bin/sh

. /usr/lib/wrtgram/common

while true; do
    curl -s ${CURL_TLS} -X POST "${WRTGRAM_API}/sendChatAction" \
        -d "chat_id=${WRTGRAM_CHAT_ID}" \
        -d "action=typing" \
        | logger -t "telegram_bot[$$]" -p daemon.info
    sleep 6
done
